### PR TITLE
feat(repo): update pnpm to v8

### PR DESCRIPTION
**Pull request by mandarini**
# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests

# Description

Updated `pnpm` to v8, and setting the version specifically in `package.json`

# Use cases and why

- 1. This will avoid potential `ERR_PNPM_OUTDATED_LOCKFILE ` errors in CI.

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/qwikifiers/qwik-nx/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by dmitry-stepanenko** [comment]
Thank you, @mandarini!

**Comment by dmitry-stepanenko** [comment]
Looks like setup is failing. Probably it's just needed to update version 7 to 8 here https://github.com/qwikifiers/qwik-nx/blob/main/.github/actions/setup/action.yml#L28

**Comment by mandarini** [comment]
Done! :D Let's see!

**Comment by dmitry-stepanenko** [comment]
@mandarini it worked just fine, thanks again for the contribution! 🙂

**Comment by mandarini** [comment]
Thank youuuuuu!!!! :D

**Pull request merged**
