### PR TITLE
chore: migrate to nx 16

### PR DESCRIPTION
**Pull request by dmitry-stepanenko**

### CODE REVIEW

**Comment by dmitry-stepanenko** [comment]
@sebastiandg7 for v16 I have to disable playwright due to its incompatibility with changes in nx. Will you be able to migrate it?

**Comment by sebastiandg7** [comment]
@dmitry-stepanenko absolutely! I'm currently working on that.

**Comment by dmitry-stepanenko** [comment]
> @dmitry-stepanenko absolutely! I'm currently working on that.

this is awesome, thank you! 🎉

**Comment by sebastiandg7** [comment]
@dmitry-stepanenko `@nxkit/playwright` v3.0.0 released! Added compatibility with Nx v16.

**Comment by dmitry-stepanenko** [comment]
@sebastiandg7 thanks a lot!

**Pull request merged**
